export const LOAD_COUNTRY_DATA = 'LOAD_COUNTRY_DATA';
export const LOAD_CONTINENT_DATA = 'LOAD_CONTINENT_DATA';

export const ADD_COUNTRY_DATA = 'ADD_COUNTRY_DATA';
export const DELETE_COUNTRY_DATA = 'DELETE_COUNTRY_DATA';

export const SELECTED_COUNTRY = 'SELECTED_COUNTRY';
export const SELECTED_TYPE = 'SELECTED_TYPE';
